config/routes.rb
ThespeeApp::Application.routes.draw do
  resources :categories

  resources :schools

  mount StripeEvent::Engine => '/stripe'
  
  get "content/monthly"

  get "content/quarterly"

  get "content/yearly"

  authenticated :user do
    root :to => 'home#main', :as => :home
  end
  root :to => "home#main", :as => :home
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
end

app/models/school.rb
class School < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  belongs_to :category

  acts_as_gmappable   :latitude => 'latitude', :longitude => 'longitude', :process_geocoding => true,
  					  #:lat => 'latitude', :lng => 'longitude', :process_geocoding => :geocode?,
	                  :address => "street", :normalized_address => "street",
                      :msg => "Sorry, not even Google could figure out where that is"

  #geocoded_by :address   # can also be an IP address
  #after_validation :geocode          # auto-fetch coordinates

  attr_accessible :street, :category_id, :category_name, :email_address, :city, :instructors, :long_description, :name, :phone, :price, :short_description, :state, :verified, :zip


  def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
	"#{self.street}, #{self.city}, #{self.zip}" 
  end

  def gmaps4rails_infowindow
      "<h4>#{self.name}</h4><p>#{self.street}</p>"
  end

  def geocode?
  (!address.blank? && (lat.blank? || lng.blank?)) || address_changed?
  end

  def to_label 
    "#{category_name}" 
   end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :index
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    @markers = School.all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    if request.path != school_path(@school)
      redirect_to @school, status: :moved_permanently
    end

    @marker = @school.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new

    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
    @category = Category.find(:all)
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :phone %>
    <%= f.input :email_address %>
    <%= f.input :short_description %>
    <%= f.input :long_description %>
    <%= f.association :category, :include_blank => false %>
    <%= f.input :instructors %>
    <%= f.input :verified %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<div class="table table-striped">
<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Short description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
 <tbody>
<tr>
    <td><%= school.name %></td>
    <td><%= school.city %></td>
    <td><%= school.zip %></td>
    <td><%= school.phone %></td>
    <td><%= school.short_description %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</tbody>
<% end %>
</table>
</div>

<br />

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

  <div id= "school-title">
    <h1><%= @school.name %></h1>
  </div>

  <p class="lead">
    <%= @school.short_description %>
  </p>

  <address>
    <b>
      <%= @school.street %><br/>
      <!--<%= @school.city %>, <%= @school.state %> <%= @school.zip %><br/>-->
      <%= @school.phone %><br/>
      <%= @school.email_address %>
    </b>
  </address>

  <div>
      <%= gmaps4rails(@marker) %>
  </div>

  <div id="school-body">
    <div class="container">
      <h4><%= @school.name %></h4>
      <p><%= @school.long_description %></p>
    </div>
  </div>

  <p>
    <b>Category:</b>
    <%= @school.category.name %>
  </p>

  <p>
    <b>Instructors:</b>
    <%= @school.instructors %>
  </p>

  <p>
    <b>Verified:</b>
    <%= @school.verified %>
  </p>

  <p>
    <b>Price:</b>
    <%= @school.price %>
  </p>



<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>
<div>
  <%= render 'layouts/footer' %>
</div>