config/routes.rb
ThespeeApp::Application.routes.draw do
  resources :categories

  resources :schools

  mount StripeEvent::Engine => '/stripe'
  
  get "content/monthly"

  get "content/quarterly"

  get "content/yearly"

  authenticated :user do
    root :to => 'home#main', :as => :home
  end
  root :to => "home#main", :as => :home
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
end

app/views/layouts/_footer.html.erb
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="span3">
                <div class="widget">
                    <h3 class="widget-title">About Us</h3> 
                    <p>Proin fermentum sollicitudin ante, sed tempor eros molestie id. Donec volutpat odio eu mi imperdiet nec laoreet diam venenatis. Proin fermentum sollicitudin ante, sed tempor eros molestie id. Donec volutpat odio eu mi imperdiet nec laoreet diam venenatis.</p>
                </div>
            </div>
            <div class="span3">                  
                <div class="widget recent-tweets">
                    <h3 class="widget-title">Latest Tweets</h3>
                    <ul>
                        <li>You know you're good in <a href="">#WordPress</a> if you can use WordPress in any language.<a href="" title="view tweet on twitter"> about a day ago</a></li>
                        <li>Confucius: Tell me and I forget. Show me and I remember. Let me do and I understand.<a href="" title="view tweet on twitter"> about 6 days ago</a></li>
                    </ul>
                </div>
            </div>
            <div class="span3">
                <h3 class="widget-title">Where We Are</h3>
                <p class="faddress">5482 Wilshire Blvd Suite #101 <br />Los Angeles, CA 90036</p>
                <p class="phone">Phone: (323) 800-4064</p>
                <p class="email">thespee.site@gmail.com</p>
            </div>
            <div class="span3">
                <div class="widget photo-stream">
                    <h3 class="widget-title">Stay Connected.</h3>
                    <ul>
                        <li><a href=""><%= image_tag "flickr/flickr_1.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_2.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_3.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_4.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_5.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_6.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_7.jpg" %></a></li>
                        <li><a href=""><%= image_tag "flickr/flickr_8.jpg" %></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<div id="copyrights">
    <div class="container">
        <div class="row">
            <div class="terms-condition span7">
                <ul class="copyright">
                    <li>TM + © 2012 DHAKADESK DEV. All rights reserved</li>
                    <li><a href="">Legal Notice</a></li>
                    <li><a href="">Terms &amp; Conditions</a></li>
                </ul>
            </div>
            <div class="span5">
                <ul class="social-links pull-right">
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="Facebook"><i class="icon-facebook"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="Twitter"><i class="icon-twitter"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="GitHub"><i class="icon-github"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="LinkedIn"><i class="icon-linkedin"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="Pinterest"><i class="icon-pinterest"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="Google Plus"><i class="icon-google-plus"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="RSS"><i class="icon-rss"></i></a></li>
                    <li><a href="" rel="tooltip" data-placement="top" data-original-title="Other"><i class="icon-sign-blank"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
     <div class="span4">
         <div  class="logo">
             <h3><a href="index.html">THESP [EE]</a> <small>Verified Reviews</small></h3>
         </div>
     </div>
     <div class="span8">
         <div class="menu">
             <ul class="main-menu">
        <li>
          <%= link_to 'Home', home_path %>
        </li>
		<% if user_signed_in? %>
		   <li>
		   <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
		   </li>
		 <% else %>
		   <li>
		   <%= link_to 'Login', new_user_session_path %>  
		   </li>
		 <% end %>
		 <% if user_signed_in? %>
		   <li>
		   <%= link_to 'Edit account', edit_user_registration_path %>
		   </li>
		   <% if current_user.has_role? :admin %>
		     <li>
		     <%= link_to 'Admin', users_path %>
		     </li>
		   <% end %>
		 <% end %>
          <li><%= link_to 'Schools', schools_path %></li>
 		    	<li><a href="about.html">About Us</a></li>
  		    <li><a href="docs/index.html">Features</a>
   		    <ul>
    		    <li><a href="docs/base-css.html">Base CSS</a></li>
		    	<li><a href="docs/components.html">Components</a></li>
   			    <li><a href="p_table.html">Pricing Tables</a></li>
    			<li><a href="gallery.html">Photo Gallery</a></li>
  		    		<li><a href="docs/javascript.html">JavaScript</a></li>
   		    	<li><a href="#">Third Level Item <i class="icon-caret-right pull-right"></i></a>
       				<ul>
        				<li><a href="#">Just an example</a></li>
	        			<li><a href="#">Of a third level</a></li>
		        		<li><a href="#">Dropdown link</a></li>
 		        </ul>
 						</li>
     				</ul>
      		</li>
       	<li><a href="portfolio.html">Portfolio</a>
        	<ul>
         	<li><a href="portfolio.html">3 Columns - Default</a></li>
 			    		<li><a href="portfolio_4_columns.html">4 Columns</a></li>
  			    	<li><a href="portfolio_2_columns.html">2 Columns</a></li>
     		<li><a href="portfolio_item.html">Portfolio Single Item</a></li>
     				</ul>
      		</li>
       	<li><a href="blog.html">Blog</a>
    		<ul>
 			    		<li><a href="blog.html">Default Layout</a></li>
   			    <li><a href="blog_post.html">Single Post Item</a></li>
	        </ul>
   		</li>
 		    	<li><a href="contact.html">Contact</a></li>
       </ul>
         </div>
     </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Thespee App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Thespee App" %>">
    <link rel='stylesheet' id='mission-font-css'  href='http://fonts.googleapis.com/css?family=Oswald&#038;ver=3.3.2' type='text/css' media='all' />
    <link rel="shortcut icon" href="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    
	<header id="header" class="navbar-fixed-top">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </header>


    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <%= yield :scripts %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>